[package]
name = "four"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
erased-serde = { workspace = true }
four-macros = { workspace = true }
regex.workspace = true
serde = { workspace = true }
thiserror.workspace = true

[dev-dependencies]
serde_json = { workspace = true }
