[package]
name = "four"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
aws-config = { workspace = true, features = ["sso"] }
aws-sdk-cloudformation = { workspace = true }
aws-sdk-lambda = { workspace = true }
aws-sdk-s3 = { workspace = true }
cargo-lambda-build = { workspace = true }
cargo-lambda-metadata = { workspace = true }
cargo-lambda-remote = { workspace = true }
cargo-options = "0.7.4"
cargo_metadata = { workspace = true }
lazy_static = { workspace = true }
miette = { workspace = true }
nutype = { workspace = true, features = ["regex", "serde"] }
parse-display = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "fs"] }
uuid = { workspace = true, features = ["serde", "v4"] }
