[package]
name = "simple_lambda"
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.86"
dotenvy = "0.15.7"
four.workspace = true
four_iam.workspace = true
four_lambda.workspace = true
serde.workspace = true
serde_json.workspace = true
