[package]
name = "simple_lambda"
edition = "2021"
license = "MIT"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.86"
dotenvy = "0.15.7"
four = { version = "0.0.13", features = ["iam", "lambda"] }
serde = "1"
serde_json = "1"
