[package]
name = "simple_lambda"
edition = "2021"
license = "MIT"
rust-version = "1.80"

[dependencies]
anyhow = { workspace = true }
dotenvy = { workspace = true }
four = { workspace = true, features = ["iam", "lambda"] }
serde = { workspace = true }
serde_json = { workspace = true }
