[package]
name = "simple_lambda"
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.86"
dotenvy = "0.15.7"
four = "0.0.6"
four_iam = "0.0.6"
four_lambda = "0.0.6"
serde = "1"
serde_json = "1"
